import { dataProp } from "./interface";

const data: dataProp[] = [
  {
    name: "Afghanistan",
    iso_alpha_2_code: "AF",
    iso_alpha_3_code: "AFG",
    code: "+93",
  },
  {
    name: "Albania",
    iso_alpha_2_code: "AL",
    iso_alpha_3_code: "ALB",
    code: "+355",
  },
  {
    name: "Algeria",
    iso_alpha_2_code: "DZ",
    iso_alpha_3_code: "DZA",
    code: "+213",
  },
  {
    name: "American Samoa",
    iso_alpha_2_code: "AS",
    iso_alpha_3_code: "ASM",
    code: "+1-684",
  },
  {
    name: "Andorra",
    iso_alpha_2_code: "AD",
    iso_alpha_3_code: "AND",
    code: "+376",
  },
  {
    name: "Angola",
    iso_alpha_2_code: "AO",
    iso_alpha_3_code: "AGO",
    code: "+244",
  },
  {
    name: "Anguilla",
    iso_alpha_2_code: "AI",
    iso_alpha_3_code: "AIA",
    code: "+1-264",
  },
  {
    name: "Antarctica",
    iso_alpha_2_code: "AQ",
    iso_alpha_3_code: "ATA",
    code: "+672",
  },
  {
    name: "Antigua and Barbuda",
    iso_alpha_2_code: "AG",
    iso_alpha_3_code: "ATG",
    code: "+1-268",
  },
  {
    name: "Argentina",
    iso_alpha_2_code: "AR",
    iso_alpha_3_code: "ARG",
    code: "+54",
  },
  {
    name: "Armenia",
    iso_alpha_2_code: "AM",
    iso_alpha_3_code: "ARM",
    code: "+374",
  },
  {
    name: "Aruba",
    iso_alpha_2_code: "AW",
    iso_alpha_3_code: "ABW",
    code: "+297",
  },
  {
    name: "Australia",
    iso_alpha_2_code: "AU",
    iso_alpha_3_code: "AUS",
    code: "+61",
  },
  {
    name: "Austria",
    iso_alpha_2_code: "AT",
    iso_alpha_3_code: "AUT",
    code: "+43",
  },
  {
    name: "Azerbaijan",
    iso_alpha_2_code: "AZ",
    iso_alpha_3_code: "AZE",
    code: "+994",
  },
  {
    name: "Bahamas (the)",
    iso_alpha_2_code: "BS",
    iso_alpha_3_code: "BHS",
    code: "+1-242",
  },
  {
    name: "Bahrain",
    iso_alpha_2_code: "BH",
    iso_alpha_3_code: "BHR",
    code: "+973",
  },
  {
    name: "Bangladesh",
    iso_alpha_2_code: "BD",
    iso_alpha_3_code: "BGD",
    code: "+880",
  },
  {
    name: "Barbados",
    iso_alpha_2_code: "BB",
    iso_alpha_3_code: "BRB",
    code: "+1-246",
  },
  {
    name: "Belarus",
    iso_alpha_2_code: "BY",
    iso_alpha_3_code: "BLR",
    code: "+375",
  },
  {
    name: "Belgium",
    iso_alpha_2_code: "BE",
    iso_alpha_3_code: "BEL",
    code: "+32",
  },
  {
    name: "Belize",
    iso_alpha_2_code: "BZ",
    iso_alpha_3_code: "BLZ",
    code: "+501",
  },
  {
    name: "Benin",
    iso_alpha_2_code: "BJ",
    iso_alpha_3_code: "BEN",
    code: "+229",
  },
  {
    name: "Bermuda",
    iso_alpha_2_code: "BM",
    iso_alpha_3_code: "BMU",
    code: "+1-441",
  },
  {
    name: "Bhutan",
    iso_alpha_2_code: "BT",
    iso_alpha_3_code: "BTN",
    code: "+975",
  },
  {
    name: "Bolivia (Plurinational State)",
    iso_alpha_2_code: "BO",
    iso_alpha_3_code: "BOL",
    code: "+591",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    iso_alpha_2_code: "BQ",
    iso_alpha_3_code: "BES",
    code: "+599",
  },
  {
    name: "Bosnia and Herzegovina",
    iso_alpha_2_code: "BA",
    iso_alpha_3_code: "BIH",
    code: "+387",
  },
  {
    name: "Botswana",
    iso_alpha_2_code: "BW",
    iso_alpha_3_code: "BWA",
    code: "+267",
  },
  {
    name: "Bouvet Island",
    iso_alpha_2_code: "BV",
    iso_alpha_3_code: "BVT",
    code: "+47",
  },
  {
    name: "Brazil",
    iso_alpha_2_code: "BR",
    iso_alpha_3_code: "BRA",
    code: "+55",
  },
  {
    name: "British Indian Ocean Territory (the)",
    iso_alpha_2_code: "IO",
    iso_alpha_3_code: "IOT",
    code: "+246",
  },
  {
    name: "Brunei Darussalam",
    iso_alpha_2_code: "BN",
    iso_alpha_3_code: "BRN",
    code: "+673",
  },
  {
    name: "Bulgaria",
    iso_alpha_2_code: "BG",
    iso_alpha_3_code: "BGR",
    code: "+359",
  },
  {
    name: "Burkina Faso",
    iso_alpha_2_code: "BF",
    iso_alpha_3_code: "BFA",
    code: "+226",
  },
  {
    name: "Burundi",
    iso_alpha_2_code: "BI",
    iso_alpha_3_code: "BDI",
    code: "+257",
  },
  {
    name: "Cabo Verde",
    iso_alpha_2_code: "CV",
    iso_alpha_3_code: "CPV",
    code: "+238",
  },
  {
    name: "Cambodia",
    iso_alpha_2_code: "KH",
    iso_alpha_3_code: "KHM",
    code: "+855",
  },
  {
    name: "Cameroon",
    iso_alpha_2_code: "CM",
    iso_alpha_3_code: "CMR",
    code: "+237",
  },
  {
    name: "Canada",
    iso_alpha_2_code: "CA",
    iso_alpha_3_code: "CAN",
    code: "+1",
  },
  {
    name: "Cayman Islands (the)",
    iso_alpha_2_code: "KY",
    iso_alpha_3_code: "CYM",
    code: "+1-345",
  },
  {
    name: "Central African Republic (the)",
    iso_alpha_2_code: "CF",
    iso_alpha_3_code: "CAF",
    code: "+236",
  },
  {
    name: "Chad",
    iso_alpha_2_code: "TD",
    iso_alpha_3_code: "TCD",
    code: "+235",
  },
  {
    name: "Chile",
    iso_alpha_2_code: "CL",
    iso_alpha_3_code: "CHL",
    code: "+56",
  },
  {
    name: "China",
    iso_alpha_2_code: "CN",
    iso_alpha_3_code: "CHN",
    code: "+86",
  },
  {
    name: "Christmas Island",
    iso_alpha_2_code: "CX",
    iso_alpha_3_code: "CXR",
    code: "+61",
  },
  {
    name: "Cocos (Keeling) Islands (the)",
    iso_alpha_2_code: "CC",
    iso_alpha_3_code: "CCK",
    code: "+61",
  },
  {
    name: "Colombia",
    iso_alpha_2_code: "CO",
    iso_alpha_3_code: "COL",
    code: "+57",
  },
  {
    name: "Comoros (the)",
    iso_alpha_2_code: "KM",
    iso_alpha_3_code: "COM",
    code: "+269",
  },
  {
    name: "Congo (the Democratic Republic of the)",
    iso_alpha_2_code: "CD",
    iso_alpha_3_code: "COD",
    code: "+243",
  },
  {
    name: "Congo (the)",
    iso_alpha_2_code: "CG",
    iso_alpha_3_code: "COG",
    code: "+242",
  },
  {
    name: "Cook Islands (the)",
    iso_alpha_2_code: "CK",
    iso_alpha_3_code: "COK",
    code: "+682",
  },
  {
    name: "Costa Rica",
    iso_alpha_2_code: "CR",
    iso_alpha_3_code: "CRI",
    code: "+506",
  },
  {
    name: "Croatia",
    iso_alpha_2_code: "HR",
    iso_alpha_3_code: "HRV",
    code: "+385",
  },
  {
    name: "Cuba",
    iso_alpha_2_code: "CU",
    iso_alpha_3_code: "CUB",
    code: "+53",
  },
  {
    name: "Curaçao",
    iso_alpha_2_code: "CW",
    iso_alpha_3_code: "CUW",
    code: "+599",
  },
  {
    name: "Cyprus",
    iso_alpha_2_code: "CY",
    iso_alpha_3_code: "CYP",
    code: "+357",
  },
  {
    name: "Czechia",
    iso_alpha_2_code: "CZ",
    iso_alpha_3_code: "CZE",
    code: "+420",
  },
  {
    name: "Côte d’Ivoire",
    iso_alpha_2_code: "CI",
    iso_alpha_3_code: "CIV",
    code: "+225",
  },
  {
    name: "Denmark",
    iso_alpha_2_code: "DK",
    iso_alpha_3_code: "DNK",
    code: "+45",
  },
  {
    name: "Djibouti",
    iso_alpha_2_code: "DJ",
    iso_alpha_3_code: "DJI",
    code: "+253",
  },
  {
    name: "Dominica",
    iso_alpha_2_code: "DM",
    iso_alpha_3_code: "DMA",
    code: "+1",
  },
  {
    name: "Dominican Republic (the)",
    iso_alpha_2_code: "DO",
    iso_alpha_3_code: "DOM",
    code: "+1",
  },
  {
    name: "Ecuador",
    iso_alpha_2_code: "EC",
    iso_alpha_3_code: "ECU",
    code: "+593",
  },
  {
    name: "Egypt",
    iso_alpha_2_code: "EG",
    iso_alpha_3_code: "EGY",
    code: "+20",
  },
  {
    name: "El Salvador",
    iso_alpha_2_code: "SV",
    iso_alpha_3_code: "SLV",
    code: "+503",
  },
  {
    name: "Equatorial Guinea",
    iso_alpha_2_code: "GQ",
    iso_alpha_3_code: "GNQ",
    code: "+240",
  },
  {
    name: "Eritrea",
    iso_alpha_2_code: "ER",
    iso_alpha_3_code: "ERI",
    code: "+291",
  },
  {
    name: "Estonia",
    iso_alpha_2_code: "EE",
    iso_alpha_3_code: "EST",
    code: "+372",
  },
  {
    name: "Eswatini",
    iso_alpha_2_code: "SZ",
    iso_alpha_3_code: "SWZ",
    code: "+268",
  },
  {
    name: "Ethiopia",
    iso_alpha_2_code: "ET",
    iso_alpha_3_code: "ETH",
    code: "+251",
  },
  {
    name: "Falkland Islands (the) [Malvinas]",
    iso_alpha_2_code: "FK",
    iso_alpha_3_code: "FLK",
    code: "+500",
  },
  {
    name: "Faroe Islands (the)",
    iso_alpha_2_code: "FO",
    iso_alpha_3_code: "FRO",
    code: "+298",
  },
  {
    name: "Fiji",
    iso_alpha_2_code: "FJ",
    iso_alpha_3_code: "FJI",
    code: "+679",
  },
  {
    name: "Finland",
    iso_alpha_2_code: "FI",
    iso_alpha_3_code: "FIN",
    code: "+358",
  },
  {
    name: "France",
    iso_alpha_2_code: "FR",
    iso_alpha_3_code: "FRA",
    code: "+33",
  },
  {
    name: "French Guiana",
    iso_alpha_2_code: "GF",
    iso_alpha_3_code: "GUF",
    code: "+594",
  },
  {
    name: "French Polynesia",
    iso_alpha_2_code: "PF",
    iso_alpha_3_code: "PYF",
    code: "+689",
  },
  {
    name: "French Southern Territories (the)",
    iso_alpha_2_code: "TF",
    iso_alpha_3_code: "ATF",
    code: "+262",
  },
  {
    name: "Gabon",
    iso_alpha_2_code: "GA",
    iso_alpha_3_code: "GAB",
    code: "+241",
  },
  {
    name: "Gambia (the)",
    iso_alpha_2_code: "GM",
    iso_alpha_3_code: "GMB",
    code: "+220",
  },
  {
    name: "Georgia",
    iso_alpha_2_code: "GE",
    iso_alpha_3_code: "GEO",
    code: "+995",
  },
  {
    name: "Germany",
    iso_alpha_2_code: "DE",
    iso_alpha_3_code: "DEU",
    code: "+49",
  },
  {
    name: "Ghana",
    iso_alpha_2_code: "GH",
    iso_alpha_3_code: "GHA",
    code: "+233",
  },
  {
    name: "Gibraltar",
    iso_alpha_2_code: "GI",
    iso_alpha_3_code: "GIB",
    code: "+350",
  },
  {
    name: "Greece",
    iso_alpha_2_code: "GR",
    iso_alpha_3_code: "GRC",
    code: "+30",
  },
  {
    name: "Greenland",
    iso_alpha_2_code: "GL",
    iso_alpha_3_code: "GRL",
    code: "+299",
  },
  {
    name: "Grenada",
    iso_alpha_2_code: "GD",
    iso_alpha_3_code: "GRD",
    code: "+1-473",
  },
  {
    name: "Guadeloupe",
    iso_alpha_2_code: "GP",
    iso_alpha_3_code: "GLP",
    code: "+590",
  },
  {
    name: "Guam",
    iso_alpha_2_code: "GU",
    iso_alpha_3_code: "GUM",
    code: "+1-671",
  },
  {
    name: "Guatemala",
    iso_alpha_2_code: "GT",
    iso_alpha_3_code: "GTM",
    code: "+502",
  },
  {
    name: "Guernsey",
    iso_alpha_2_code: "GG",
    iso_alpha_3_code: "GGY",
    code: "+44-1481",
  },
  {
    name: "Guinea",
    iso_alpha_2_code: "GN",
    iso_alpha_3_code: "GIN",
    code: "+224",
  },
  {
    name: "Guinea-Bissau",
    iso_alpha_2_code: "GW",
    iso_alpha_3_code: "GNB",
    code: "+245",
  },
  {
    name: "Guyana",
    iso_alpha_2_code: "GY",
    iso_alpha_3_code: "GUY",
    code: "+592",
  },
  {
    name: "Haiti",
    iso_alpha_2_code: "HT",
    iso_alpha_3_code: "HTI",
    code: "+509",
  },
  {
    name: "Heard Island and McDonald Islands",
    iso_alpha_2_code: "HM",
    iso_alpha_3_code: "HMD",
    code: "+672",
  },
  {
    name: "Holy See (the)",
    iso_alpha_2_code: "VA",
    iso_alpha_3_code: "VAT",
    code: "+379",
  },
  {
    name: "Honduras",
    iso_alpha_2_code: "HN",
    iso_alpha_3_code: "HND",
    code: "+504",
  },
  {
    name: "Hong Kong",
    iso_alpha_2_code: "HK",
    iso_alpha_3_code: "HKG",
    code: "+852",
  },
  {
    name: "Hungary",
    iso_alpha_2_code: "HU",
    iso_alpha_3_code: "HUN",
    code: "+36",
  },
  {
    name: "Iceland",
    iso_alpha_2_code: "IS",
    iso_alpha_3_code: "ISL",
    code: "+354",
  },
  {
    name: "India",
    iso_alpha_2_code: "IN",
    iso_alpha_3_code: "IND",
    code: "+91",
  },
  {
    name: "Indonesia",
    iso_alpha_2_code: "ID",
    iso_alpha_3_code: "IDN",
    code: "+62",
  },
  {
    name: "Iran (Islamic Republic of)",
    iso_alpha_2_code: "IR",
    iso_alpha_3_code: "IRN",
    code: "+98",
  },
  {
    name: "Iraq",
    iso_alpha_2_code: "IQ",
    iso_alpha_3_code: "IRQ",
    code: "+964",
  },
  {
    name: "Ireland",
    iso_alpha_2_code: "IE",
    iso_alpha_3_code: "IRL",
    code: "+353",
  },
  {
    name: "Isle of Man",
    iso_alpha_2_code: "IM",
    iso_alpha_3_code: "IMN",
    code: "+44",
  },
  {
    name: "Israel",
    iso_alpha_2_code: "IL",
    iso_alpha_3_code: "ISR",
    code: "+972",
  },
  {
    name: "Italy",
    iso_alpha_2_code: "IT",
    iso_alpha_3_code: "ITA",
    code: "+39",
  },
  {
    name: "Jamaica",
    iso_alpha_2_code: "JM",
    iso_alpha_3_code: "JAM",
    code: "+1-876",
  },
  {
    name: "Japan",
    iso_alpha_2_code: "JP",
    iso_alpha_3_code: "JPN",
    code: "+81",
  },
  {
    name: "Jersey",
    iso_alpha_2_code: "JE",
    iso_alpha_3_code: "JEY",
    code: "+44-1534",
  },
  {
    name: "Jordan",
    iso_alpha_2_code: "JO",
    iso_alpha_3_code: "JOR",
    code: "+962",
  },
  {
    name: "Kazakhstan",
    iso_alpha_2_code: "KZ",
    iso_alpha_3_code: "KAZ",
    code: "+7",
  },
  {
    name: "Kenya",
    iso_alpha_2_code: "KE",
    iso_alpha_3_code: "KEN",
    code: "+254",
  },
  {
    name: "Kiribati",
    iso_alpha_2_code: "KI",
    iso_alpha_3_code: "KIR",
    code: "+686",
  },
  {
    name: "Korea (the Democratic People’s Republic of)",
    iso_alpha_2_code: "KP",
    iso_alpha_3_code: "PRK",
    code: "+850",
  },
  {
    name: "Korea (the Republic of)",
    iso_alpha_2_code: "KR",
    iso_alpha_3_code: "KOR",
    code: "+82",
  },
  {
    name: "Kuwait",
    iso_alpha_2_code: "KW",
    iso_alpha_3_code: "KWT",
    code: "+965",
  },
  {
    name: "Kyrgyzstan",
    iso_alpha_2_code: "KG",
    iso_alpha_3_code: "KGZ",
    code: "+996",
  },
  {
    name: "Lao People’s Democratic Republic (the)",
    iso_alpha_2_code: "LA",
    iso_alpha_3_code: "LAO",
    code: "+856",
  },
  {
    name: "Latvia",
    iso_alpha_2_code: "LV",
    iso_alpha_3_code: "LVA",
    code: "+371",
  },
  {
    name: "Lebanon",
    iso_alpha_2_code: "LB",
    iso_alpha_3_code: "LBN",
    code: "+961",
  },
  {
    name: "Lesotho",
    iso_alpha_2_code: "LS",
    iso_alpha_3_code: "LSO",
    code: "+266",
  },
  {
    name: "Liberia",
    iso_alpha_2_code: "LR",
    iso_alpha_3_code: "LBR",
    code: "+231",
  },
  {
    name: "Libya",
    iso_alpha_2_code: "LY",
    iso_alpha_3_code: "LBY",
    code: "+218",
  },
  {
    name: "Liechtenstein",
    iso_alpha_2_code: "LI",
    iso_alpha_3_code: "LIE",
    code: "+423",
  },
  {
    name: "Lithuania",
    iso_alpha_2_code: "LT",
    iso_alpha_3_code: "LTU",
    code: "+370",
  },
  {
    name: "Luxembourg",
    iso_alpha_2_code: "LU",
    iso_alpha_3_code: "LUX",
    code: "+352",
  },
  {
    name: "Macao",
    iso_alpha_2_code: "MO",
    iso_alpha_3_code: "MAC",
    code: "+853",
  },
  {
    name: "Madagascar",
    iso_alpha_2_code: "MG",
    iso_alpha_3_code: "MDG",
    code: "+261",
  },
  {
    name: "Malawi",
    iso_alpha_2_code: "MW",
    iso_alpha_3_code: "MWI",
    code: "+265",
  },
  {
    name: "Malaysia",
    iso_alpha_2_code: "MY",
    iso_alpha_3_code: "MYS",
    code: "+60",
  },
  {
    name: "Maldives",
    iso_alpha_2_code: "MV",
    iso_alpha_3_code: "MDV",
    code: "+960",
  },
  {
    name: "Mali",
    iso_alpha_2_code: "ML",
    iso_alpha_3_code: "MLI",
    code: "+223",
  },
  {
    name: "Malta",
    iso_alpha_2_code: "MT",
    iso_alpha_3_code: "MLT",
    code: "+356",
  },
  {
    name: "Marshall Islands (the)",
    iso_alpha_2_code: "MH",
    iso_alpha_3_code: "MHL",
    code: "+692",
  },
  {
    name: "Martinique",
    iso_alpha_2_code: "MQ",
    iso_alpha_3_code: "MTQ",
    code: "+596",
  },
  {
    name: "Mauritania",
    iso_alpha_2_code: "MR",
    iso_alpha_3_code: "MRT",
    code: "+222",
  },
  {
    name: "Mauritius",
    iso_alpha_2_code: "MU",
    iso_alpha_3_code: "MUS",
    code: "+230",
  },
  {
    name: "Mayotte",
    iso_alpha_2_code: "YT",
    iso_alpha_3_code: "MYT",
    code: "+262",
  },
  {
    name: "Mexico",
    iso_alpha_2_code: "MX",
    iso_alpha_3_code: "MEX",
    code: "+52",
  },
  {
    name: "Micronesia (Federated States of)",
    iso_alpha_2_code: "FM",
    iso_alpha_3_code: "FSM",
    code: "+691",
  },
  {
    name: "Moldova (the Republic of)",
    iso_alpha_2_code: "MD",
    iso_alpha_3_code: "MDA",
    code: "+373",
  },
  {
    name: "Monaco",
    iso_alpha_2_code: "MC",
    iso_alpha_3_code: "MCO",
    code: "+377",
  },
  {
    name: "Mongolia",
    iso_alpha_2_code: "MN",
    iso_alpha_3_code: "MNG",
    code: "+976",
  },
  {
    name: "Montenegro",
    iso_alpha_2_code: "ME",
    iso_alpha_3_code: "MNE",
    code: "+382",
  },
  {
    name: "Montserrat",
    iso_alpha_2_code: "MS",
    iso_alpha_3_code: "MSR",
    code: "+1-664",
  },
  {
    name: "Morocco",
    iso_alpha_2_code: "MA",
    iso_alpha_3_code: "MAR",
    code: "+212",
  },
  {
    name: "Mozambique",
    iso_alpha_2_code: "MZ",
    iso_alpha_3_code: "MOZ",
    code: "+258",
  },
  {
    name: "Myanmar",
    iso_alpha_2_code: "MM",
    iso_alpha_3_code: "MMR",
    code: "+95",
  },
  {
    name: "Namibia",
    iso_alpha_2_code: "NA",
    iso_alpha_3_code: "NAM",
    code: "+264",
  },
  {
    name: "Nauru",
    iso_alpha_2_code: "NR",
    iso_alpha_3_code: "NRU",
    code: "+674",
  },
  {
    name: "Nepal",
    iso_alpha_2_code: "NP",
    iso_alpha_3_code: "NPL",
    code: "+977",
  },
  {
    name: "Netherlands (the)",
    iso_alpha_2_code: "NL",
    iso_alpha_3_code: "NLD",
    code: "+31",
  },
  {
    name: "New Caledonia",
    iso_alpha_2_code: "NC",
    iso_alpha_3_code: "NCL",
    code: "+687",
  },
  {
    name: "New Zealand",
    iso_alpha_2_code: "NZ",
    iso_alpha_3_code: "NZL",
    code: "+64",
  },
  {
    name: "Nicaragua",
    iso_alpha_2_code: "NI",
    iso_alpha_3_code: "NIC",
    code: "+505",
  },
  {
    name: "Niger (the)",
    iso_alpha_2_code: "NE",
    iso_alpha_3_code: "NER",
    code: "+227",
  },
  {
    name: "Nigeria",
    iso_alpha_2_code: "NG",
    iso_alpha_3_code: "NGA",
    code: "+234",
  },
  {
    name: "Niue",
    iso_alpha_2_code: "NU",
    iso_alpha_3_code: "NIU",
    code: "+683",
  },
  {
    name: "Norfolk Island",
    iso_alpha_2_code: "NF",
    iso_alpha_3_code: "NFK",
    code: "+672",
  },
  {
    name: "Northern Mariana Islands (the)",
    iso_alpha_2_code: "MP",
    iso_alpha_3_code: "MNP",
    code: "+1-670",
  },
  {
    name: "Norway",
    iso_alpha_2_code: "NO",
    iso_alpha_3_code: "NOR",
    code: "+47",
  },
  {
    name: "Oman",
    iso_alpha_2_code: "OM",
    iso_alpha_3_code: "OMN",
    code: "+968",
  },
  {
    name: "Pakistan",
    iso_alpha_2_code: "PK",
    iso_alpha_3_code: "PAK",
    code: "+92",
  },
  {
    name: "Palau",
    iso_alpha_2_code: "PW",
    iso_alpha_3_code: "PLW",
    code: "+680",
  },
  {
    name: "Palestine, State of",
    iso_alpha_2_code: "PS",
    iso_alpha_3_code: "PSE",
    code: "+970",
  },
  {
    name: "Panama",
    iso_alpha_2_code: "PA",
    iso_alpha_3_code: "PAN",
    code: "+507",
  },
  {
    name: "Papua New Guinea",
    iso_alpha_2_code: "PG",
    iso_alpha_3_code: "PNG",
    code: "+675",
  },
  {
    name: "Paraguay",
    iso_alpha_2_code: "PY",
    iso_alpha_3_code: "PRY",
    code: "+595",
  },
  {
    name: "Peru",
    iso_alpha_2_code: "PE",
    iso_alpha_3_code: "PER",
    code: "+51",
  },
  {
    name: "Philippines (the)",
    iso_alpha_2_code: "PH",
    iso_alpha_3_code: "PHL",
    code: "+63",
  },
  {
    name: "Pitcairn",
    iso_alpha_2_code: "PN",
    iso_alpha_3_code: "PCN",
    code: "+64",
  },
  {
    name: "Poland",
    iso_alpha_2_code: "PL",
    iso_alpha_3_code: "POL",
    code: "+48",
  },
  {
    name: "Portugal",
    iso_alpha_2_code: "PT",
    iso_alpha_3_code: "PRT",
    code: "+351",
  },
  {
    name: "Puerto Rico",
    iso_alpha_2_code: "PR",
    iso_alpha_3_code: "PRI",
    code: "+1",
  },
  {
    name: "Qatar",
    iso_alpha_2_code: "QA",
    iso_alpha_3_code: "QAT",
    code: "+974",
  },
  {
    name: "Republic of North Macedonia",
    iso_alpha_2_code: "MK",
    iso_alpha_3_code: "MKD",
    code: "+389",
  },
  {
    name: "Romania",
    iso_alpha_2_code: "RO",
    iso_alpha_3_code: "ROU",
    code: "+40",
  },
  {
    name: "Russian Federation (the)",
    iso_alpha_2_code: "RU",
    iso_alpha_3_code: "RUS",
    code: "+7",
  },
  {
    name: "Rwanda",
    iso_alpha_2_code: "RW",
    iso_alpha_3_code: "RWA",
    code: "+250",
  },
  {
    name: "Réunion",
    iso_alpha_2_code: "RE",
    iso_alpha_3_code: "REU",
    code: "+262",
  },
  {
    name: "Saint Barthélemy",
    iso_alpha_2_code: "BL",
    iso_alpha_3_code: "BLM",
    code: "+590",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso_alpha_2_code: "SH",
    iso_alpha_3_code: "SHN",
    code: "+290",
  },
  {
    name: "Saint Kitts and Nevis",
    iso_alpha_2_code: "KN",
    iso_alpha_3_code: "KNA",
    code: "+1-869",
  },
  {
    name: "Saint Lucia",
    iso_alpha_2_code: "LC",
    iso_alpha_3_code: "LCA",
    code: "+1-758",
  },
  {
    name: "Saint Martin (French part)",
    iso_alpha_2_code: "MF",
    iso_alpha_3_code: "MAF",
    code: "+721",
  },
  {
    name: "Saint Pierre and Miquelon",
    iso_alpha_2_code: "PM",
    iso_alpha_3_code: "SPM",
    code: "+508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso_alpha_2_code: "VC",
    iso_alpha_3_code: "VCT",
    code: "+1-784",
  },
  {
    name: "Samoa",
    iso_alpha_2_code: "WS",
    iso_alpha_3_code: "WSM",
    code: "+685",
  },
  {
    name: "San Marino",
    iso_alpha_2_code: "SM",
    iso_alpha_3_code: "SMR",
    code: "+378",
  },
  {
    name: "Sao Tome and Principe",
    iso_alpha_2_code: "ST",
    iso_alpha_3_code: "STP",
    code: "+239",
  },
  {
    name: "Saudi Arabia",
    iso_alpha_2_code: "SA",
    iso_alpha_3_code: "SAU",
    code: "+966",
  },
  {
    name: "Senegal",
    iso_alpha_2_code: "SN",
    iso_alpha_3_code: "SEN",
    code: "+221",
  },
  {
    name: "Serbia",
    iso_alpha_2_code: "RS",
    iso_alpha_3_code: "SRB",
    code: "+381",
  },
  {
    name: "Seychelles",
    iso_alpha_2_code: "SC",
    iso_alpha_3_code: "SYC",
    code: "+248",
  },
  {
    name: "Sierra Leone",
    iso_alpha_2_code: "SL",
    iso_alpha_3_code: "SLE",
    code: "+232",
  },
  {
    name: "Singapore",
    iso_alpha_2_code: "SG",
    iso_alpha_3_code: "SGP",
    code: "+65",
  },
  {
    name: "Sint Maarten (Dutch part)",
    iso_alpha_2_code: "SX",
    iso_alpha_3_code: "SXM",
    code: "+721",
  },
  {
    name: "Slovakia",
    iso_alpha_2_code: "SK",
    iso_alpha_3_code: "SVK",
    code: "+421",
  },
  {
    name: "Slovenia",
    iso_alpha_2_code: "SI",
    iso_alpha_3_code: "SVN",
    code: "+386",
  },
  {
    name: "Solomon Islands",
    iso_alpha_2_code: "SB",
    iso_alpha_3_code: "SLB",
    code: "+677",
  },
  {
    name: "Somalia",
    iso_alpha_2_code: "SO",
    iso_alpha_3_code: "SOM",
    code: "+252",
  },
  {
    name: "South Africa",
    iso_alpha_2_code: "ZA",
    iso_alpha_3_code: "ZAF",
    code: "+27",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    iso_alpha_2_code: "GS",
    iso_alpha_3_code: "SGS",
    code: "+500",
  },
  {
    name: "South Sudan",
    iso_alpha_2_code: "SS",
    iso_alpha_3_code: "SSD",
    code: "+211",
  },
  {
    name: "Spain",
    iso_alpha_2_code: "ES",
    iso_alpha_3_code: "ESP",
    code: "+34",
  },
  {
    name: "Sri Lanka",
    iso_alpha_2_code: "LK",
    iso_alpha_3_code: "LKA",
    code: "+94",
  },
  {
    name: "Sudan (the)",
    iso_alpha_2_code: "SD",
    iso_alpha_3_code: "SDN",
    code: "+249",
  },
  {
    name: "Suriname",
    iso_alpha_2_code: "SR",
    iso_alpha_3_code: "SUR",
    code: "+597",
  },
  {
    name: "Svalbard and Jan Mayen",
    iso_alpha_2_code: "SJ",
    iso_alpha_3_code: "SJM",
    code: "+47",
  },
  {
    name: "Sweden",
    iso_alpha_2_code: "SE",
    iso_alpha_3_code: "SWE",
    code: "+46",
  },
  {
    name: "Switzerland",
    iso_alpha_2_code: "CH",
    iso_alpha_3_code: "CHE",
    code: "+41",
  },
  {
    name: "Syrian Arab Republic",
    iso_alpha_2_code: "SY",
    iso_alpha_3_code: "SYR",
    code: "+963",
  },
  {
    name: "Taiwan (Province of China)",
    iso_alpha_2_code: "TW",
    iso_alpha_3_code: "TWN",
    code: "+886",
  },
  {
    name: "Tajikistan",
    iso_alpha_2_code: "TJ",
    iso_alpha_3_code: "TJK",
    code: "+992",
  },
  {
    name: "Tanzania, United Republic of",
    iso_alpha_2_code: "TZ",
    iso_alpha_3_code: "TZA",
    code: "+255",
  },
  {
    name: "Thailand",
    iso_alpha_2_code: "TH",
    iso_alpha_3_code: "THA",
    code: "+66",
  },
  {
    name: "Timor-Leste",
    iso_alpha_2_code: "TL",
    iso_alpha_3_code: "TLS",
    code: "+670",
  },
  {
    name: "Togo",
    iso_alpha_2_code: "TG",
    iso_alpha_3_code: "TGO",
    code: "+228",
  },
  {
    name: "Tokelau",
    iso_alpha_2_code: "TK",
    iso_alpha_3_code: "TKL",
    code: "+690",
  },
  {
    name: "Tonga",
    iso_alpha_2_code: "TO",
    iso_alpha_3_code: "TON",
    code: "+676",
  },
  {
    name: "Trinidad and Tobago",
    iso_alpha_2_code: "TT",
    iso_alpha_3_code: "TTO",
    code: "+1-868",
  },
  {
    name: "Tunisia",
    iso_alpha_2_code: "TN",
    iso_alpha_3_code: "TUN",
    code: "+216",
  },
  {
    name: "Turkey",
    iso_alpha_2_code: "TR",
    iso_alpha_3_code: "TUR",
    code: "+90",
  },
  {
    name: "Turkmenistan",
    iso_alpha_2_code: "TM",
    iso_alpha_3_code: "TKM",
    code: "+993",
  },
  {
    name: "Turks and Caicos Islands (the)",
    iso_alpha_2_code: "TC",
    iso_alpha_3_code: "TCA",
    code: "+1-649",
  },
  {
    name: "Tuvalu",
    iso_alpha_2_code: "TV",
    iso_alpha_3_code: "TUV",
    code: "+688",
  },
  {
    name: "Uganda",
    iso_alpha_2_code: "UG",
    iso_alpha_3_code: "UGA",
    code: "+256",
  },
  {
    name: "Ukraine",
    iso_alpha_2_code: "UA",
    iso_alpha_3_code: "UKR",
    code: "+380",
  },
  {
    name: "United Arab Emirates (the)",
    iso_alpha_2_code: "AE",
    iso_alpha_3_code: "ARE",
    code: "+971",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    iso_alpha_2_code: "GB",
    iso_alpha_3_code: "GBR",
    code: "+44",
  },
  {
    name: "United States Minor Outlying Islands (the)",
    iso_alpha_2_code: "UM",
    iso_alpha_3_code: "UMI",
    code: "+1",
  },
  {
    name: "United States of America (the)",
    iso_alpha_2_code: "US",
    iso_alpha_3_code: "USA",
    code: "+1",
  },
  {
    name: "Uruguay",
    iso_alpha_2_code: "UY",
    iso_alpha_3_code: "URY",
    code: "+598",
  },
  {
    name: "Uzbekistan",
    iso_alpha_2_code: "UZ",
    iso_alpha_3_code: "UZB",
    code: "+998",
  },
  {
    name: "Vanuatu",
    iso_alpha_2_code: "VU",
    iso_alpha_3_code: "VUT",
    code: "+678",
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    iso_alpha_2_code: "VE",
    iso_alpha_3_code: "VEN",
    code: "+58",
  },
  {
    name: "Vietnam",
    iso_alpha_2_code: "VN",
    iso_alpha_3_code: "VNM",
    code: "+84",
  },
  {
    name: "Virgin Islands (British)",
    iso_alpha_2_code: "VG",
    iso_alpha_3_code: "VGB",
    code: "+1-284",
  },
  {
    name: "Virgin Islands (U.S.)",
    iso_alpha_2_code: "VI",
    iso_alpha_3_code: "VIR",
    code: "+1-340",
  },
  {
    name: "Wallis and Futuna",
    iso_alpha_2_code: "WF",
    iso_alpha_3_code: "WLF",
    code: "+681",
  },
  {
    name: "Western Sahara",
    iso_alpha_2_code: "EH",
    iso_alpha_3_code: "ESH",
    code: "+212",
  },
  {
    name: "Yemen",
    iso_alpha_2_code: "YE",
    iso_alpha_3_code: "YEM",
    code: "+967",
  },
];

export default data;
